### ISSUE TITLE
调用ai接口的时候，post表单没有做处理，导致有注入危险。

### ISSUE THREAD

**Issue by xia-st** [spacemeowx2/splatoon2-qqbot#3]
aichat.ts中有这样的一段代码
```
private querystring (data: Record<string, string>) {
    return Object.keys(data).sort().map(k => `${k}=${this.urlencode(data[k])}`).join('&')
}
```

这段代码中的data是来自qq群中用户输入的，这段信息应该要做一次url_encode，不然可能会有注入的危险。

**Comment by spacemeowx2** [comment]
`this.urlencode`

**Comment by spacemeowx2** [comment]
顺便一提, 转义并不能避免注入.

**Comment by xia-st** [comment]
> 顺便一提, 转义并不能避免注入.

奥对，没看仔细，主要是测试的时候，会收到这样的报错：
![_20190305111030](https://user-images.githubusercontent.com/7568382/53778415-94942a00-3f37-11e9-8424-d95f81790492.png)
还有这样的
![_20190305111337](https://user-images.githubusercontent.com/7568382/53778451-c1e0d800-3f37-11e9-8151-84cbff56846d.png)
