### ISSUE TITLE
项目如何运行

### ISSUE THREAD

**Issue by landuo** [spacemeowx2/splatoon2-qqbot#5]
大佬，可以简要说明项目如何运行么，配置的几个参数的具体意思？

**Comment by spacemeowx2** [comment]
之后我加到README中

**Comment by landuo** [comment]
十分感谢

**Comment by spacemeowx2** [comment]
已经更新

**Comment by landuo** [comment]
开启go-cqhttp服务并选择开启websocket服务后，根据README文件指引运行，提示错误。
在项目外新建docker-compose.yml运行后的错误
[docker.log](https://github.com/spacemeowx2/splatoon2-qqbot/files/7787013/docker.log)
在项目中运行 npm install后的错误
[install.log](https://github.com/spacemeowx2/splatoon2-qqbot/files/7787015/install.log)

------
node version: 16.13.1
npm version: 8.3.0

**Comment by spacemeowx2** [comment]
当年的Dockerfile可能有点问题，依赖出了问题，等我抽时间修复下

**Comment by spacemeowx2** [comment]
@landuo 确认了应该是let's encrypt证书过期的问题.

可以在 Dockerfile.prod 里临时增加一行解决:

```diff
COPY ./package.json /code
+ # https://github.com/nodejs/node-gyp/issues/1224#issuecomment-306543824
+ ENV NODE_TLS_REJECT_UNAUTHORIZED=0
RUN npm install --verbose
```

```Dockerfile
FROM node:8-alpine
LABEL maintainer="spacemeowx2@gmail.com"

RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories

RUN apk add --no-cache \
    build-base \
    g++ \
    cairo-dev \
    jpeg-dev \
    pango-dev \
    giflib-dev \
    tzdata \
    imagemagick

RUN cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

RUN mkdir /code
WORKDIR /code
COPY ./package.json /code
# https://github.com/nodejs/node-gyp/issues/1224#issuecomment-306543824
ENV NODE_TLS_REJECT_UNAUTHORIZED=0
RUN npm install --verbose

COPY . /code

CMD [ "npm", "run", "prod" ]

```

但是可能会被MITM攻击, 请注意网络环境.

**Comment by landuo** [comment]
> @landuo 确认了应该是let's encrypt证书过期的问题.
> 
> 可以在 Dockerfile.prod 里临时增加一行解决:
> 
> ```diff
> COPY ./package.json /code
> + # https://github.com/nodejs/node-gyp/issues/1224#issuecomment-306543824
> + ENV NODE_TLS_REJECT_UNAUTHORIZED=0
> RUN npm install --verbose
> ```
> 
> ```dockerfile
> FROM node:8-alpine
> LABEL maintainer="spacemeowx2@gmail.com"
> 
> RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories
> 
> RUN apk add --no-cache \
>     build-base \
>     g++ \
>     cairo-dev \
>     jpeg-dev \
>     pango-dev \
>     giflib-dev \
>     tzdata \
>     imagemagick
> 
> RUN cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
> 
> RUN mkdir /code
> WORKDIR /code
> COPY ./package.json /code
> # https://github.com/nodejs/node-gyp/issues/1224#issuecomment-306543824
> ENV NODE_TLS_REJECT_UNAUTHORIZED=0
> RUN npm install --verbose
> 
> COPY . /code
> 
> CMD [ "npm", "run", "prod" ]
> ```
> 
> 但是可能会被MITM攻击, 请注意网络环境.

添加该行后成功运行
